# Generated by Django 5.0.4 on 2024-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('displayname', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
        migrations.RenameModel(
            old_name='Drones',
            new_name='Drone',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
