# Generated by Django 5.0.4 on 2024-05-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0003_drone_url_alter_drone_battiere_alter_drone_dronename'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='userbg',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
