# Generated by Django 5.0.4 on 2024-05-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0007_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10, verbose_name='Name Theme')),
                ('bgcolor', models.TextField(max_length=6, verbose_name='Color for bg in Hex without #')),
                ('primary_color', models.TextField(max_length=6, verbose_name='primary color in Hex without #')),
                ('secondary_color', models.TextField(max_length=6, verbose_name='secondary color in Hex without #')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GlobaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togglemusic', models.BooleanField(default=True)),
                ('toggleshaders', models.BooleanField(default=True)),
                ('usertarget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logins_and_alerts.user')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='logins_and_alerts.themes')),
            ],
        ),
    ]
