# Generated by Django 4.2.14 on 2024-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0008_themes_user_is_in_team_user_is_staff_globalesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userbg',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('stars', 'Stars')], default='default', max_length=30),
        ),
    ]
