# Generated by Django 4.2.14 on 2024-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0009_alert_is_read_alter_user_userbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='dimayellow-12', max_length=15, unique=True),
        ),
    ]
