# Generated by Django 4.2.14 on 2024-07-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0011_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobaleSettings',
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
