# Generated by Django 4.2.14 on 2024-07-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins_and_alerts', '0012_delete_globalesettings_delete_themes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CUser',
        ),
    ]
